<a href="https://colab.research.google.com/github/pedrorotta/Python_B-sico-/blob/main/Clase5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Clase 5**

En esta clase veremos : 

* Numpy


## **Librería Numpy**

Es una librería que se enmarca dentro del ecosistema de [Scipy.org](https://www.scipy.org) y brinda al usuario: 

* Un tipo de objeto conocido como array. 

* Operaciones con arreglos de alta velocidad

* Algebral lineal, transformaciones de Fourier y Generación numérica aleatoria


In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

### **Arreglo de Numpy (Array)**

Un array de numpy me permite representar datos (numéricos o de texto) de manera ordenada. Normalmente se utiliza para codificación de datos como imágenes y transformaciones del algebra lineal. 

Normalmente se utilizará como una representación de matrices. 


<strong>*Mi definición*</strong>

In [3]:
# Objetos
a = np.array([3,4,5],dtype= float)
b = np.array(["hola", "como estás", "adios"], dtype=str)
print(a)
print(b)

[3. 4. 5.]
['hola' 'como estás' 'adios']


In [4]:
# Matrices : 
# Normalmente se usará letras mayúsculas para las matrices y minúsculas para los vectores
a = np.array([3,4,5])
A = np.array([[0,1,2],[1,0,1]]) #la matriz va dentro de corchetes

In [5]:
A.sort() #ordenar un objeto

In [6]:
A

array([[0, 1, 2],
       [0, 1, 1]])

In [7]:
#verificar algunos módulos
np??


### **Desarrollo de Algebra lineal**

Muchos temas de programación y análisis de datos se desarrollan, usando técnicas básicas de algebra lineal, como el dot product o el cross product. Existen además muchas más funciones de algebra lineal que se pueden usar en numpy. 

Nosotros veremos 3 : 

* Dot product 
* Cross product
* Transpuesta de una matriz 

#### **Dot Product**

El producto punto hace referencia a la combinación lineal de dos Arreglos : 

Ejemplo : Sean los arreglos en 1-D : $x = [x_1, x_2, x_3, ..., x_n]$ y $ w = [w_1,w_2,w_3,w_4,...,w_n]$.  La combinación lineal de estos dos vectores se puede definir como : 

$f(x,y) = w_1*x_1 + w_2*x_2 + w_3*x_3 + w_4*x_4 + ... + w_n*x_n = w.n$

que en python será expresado por el comando : `np.dot(x,w)`

El producto punto de un vector da como resultado un escalar. En el caso de las matrices, el valor cambia. Normalmente una matriz se define respecto al número de filas por su número de columnas en mayúscula $A_(nxm)$ : Donde n es el número de filas y m es el número de columnas 

Por ejemplo la matriz :

```
A = [[3,4,5], 
    [1,3,2]]
```
tiene 2 filas y 3 columnas por lo tanto se lee $A_(2x3)$

En el caso se tenga una matriz $B_(3x2)$. El resultado del producto punto tendrá como resultado una Matriz  $C_(2x2)$

Como conclusión, en la multiplicación matricial simple o producto punto, se cumple : 

* El producto punto de 2 vectores que tienen que tener la misma cantidad de elementos, el resultado es un escalar

* Si el producto punto se da entre 2 matrices, el número de colunmas de la primera matriz debe ser igual al número de filas de la segunda matriz 

* El resultado de un producto punto de 2 matrices dará una matriz cuyas dimensiones son los valores del número de filas de la primera matriz por el número de columnas de la segunda matriz. 


In [8]:
# Multiplicación de 2 vectores

a = np.array([0,3,1])
b = np.array([1,0,3])
c = np.dot(a,b)
print(a)
print(b)
print(c)
len(a)

[0 3 1]
[1 0 3]
3


3

In [9]:
def dot(a = a,b = b) :
  sum = 0
  for i in range(0,len(a)):
    if len(b) != len(a):
      print("error, dimensiones no coinciden")
    else: 
      e = a[i] * b[i]
      print("Iteración n°.....{}".format(i+1))
      print("La multiplicación es {} * {} que es igual a multiplicación = {}".format(a[i],b[i],e))
      print("la suma en la iteración pasada n° {} es suma = {}".format((i),sum))
      sum = sum + e
      print("la suma en esta iteración n° {} es suma = {}".format((i+1),sum))
  return sum

In [10]:
print(a)
print(b)
dot_ab = dot(a = a, b = b)
print(dot_ab)

[0 3 1]
[1 0 3]
Iteración n°.....1
La multiplicación es 0 * 1 que es igual a multiplicación = 0
la suma en la iteración pasada n° 0 es suma = 0
la suma en esta iteración n° 1 es suma = 0
Iteración n°.....2
La multiplicación es 3 * 0 que es igual a multiplicación = 0
la suma en la iteración pasada n° 1 es suma = 0
la suma en esta iteración n° 2 es suma = 0
Iteración n°.....3
La multiplicación es 1 * 3 que es igual a multiplicación = 3
la suma en la iteración pasada n° 2 es suma = 0
la suma en esta iteración n° 3 es suma = 3
3


In [15]:
#mutlplicación de 2 matrices
A = np.array([[2,3,1], 
              [1,2,0]])

B = np.array([[1,2,1],
             [1,2,3],
             [1,3,1]])
C = np.dot(A,B)


In [17]:
def imprimir(A,B,C):
  print("..........................")
  print("..........................")
  print("El primer arreglo es : ")
  print(A)
  print("..........................")
  print("..........................")
  print("El segundo arreglo es : ")
  print(B)
  print("..........................")
  print("..........................")
  print("el valor del resultado es : ")
  print(C)



In [30]:

def imprimir_valores(*args):
  for i in args:
    print("..................")
    print(i)

In [16]:
imprimir(A,B,C)

..........................
..........................
El primer arreglo es : 
[[2 3 1]
 [1 2 0]]
..........................
..........................
El segundo arreglo es : 
[[1 2 1]
 [1 2 3]
 [1 3 1]]
..........................
..........................
el valor del resultado es : 
[[ 6 13 12]
 [ 3  6  7]]


#### **Cross product**
El producto cruz hace referencia a la operación dimensional de 2 vectores o de dos matrices. Normalmente no es requisito conocer a profundidad lo que hace para este curso. Basta con aclarar que es una forma de cálculo vectorial. 

En python se puede obtener con ` np.cross(a,b)`

<img src= "http://2.bp.blogspot.com/_ureTHIKNfX4/S8MylDVIGGI/AAAAAAAAACg/yfgG8HXoyEg/s1600/prodCruz.png" heigth = "100px"></img>


In [18]:
#para vectores 

e = np.cross(a,b)
imprimir(a,b,e)

..........................
..........................
El primer arreglo es : 
[0 3 1]
..........................
..........................
El segundo arreglo es : 
[1 0 3]
..........................
..........................
el valor del resultado es : 
[ 9  1 -3]


In [19]:
## Hacer función del producto vectorial 

#### **Transpuesta**

La transpuesta de una matriz sirve en el caso queremos reconfigurar de alguna manera, una operación vectorial o matricial según sea el caso.

Los momentos en que se utiliza es cuando tenemos dos vectores con las mismas dimensiones en donde ambos son vectores fila o vectores columna (Se verá ejemplo) o matrices en que sean de igual tamaño, por ejemplo. 

<img src = "https://lh3.googleusercontent.com/proxy/n1BbCpYUIldTGNelh_F6dmfK165z1ImDihGWFiYWspQVKkOXq8QThCkSZsK8g4uJd2ryPR4rELbGoZ66a8QPzlQr4RImgXxMTMIxTgjKM_ogVgaYGZxt9YtIkGQbIPBjf4wm"></img>


en python usamos `np.transpose(x)`

In [21]:
print(np.transpose(a))

[0 3 1]


In [28]:
# Ejemplo de necesidad : 

#Sean: 
M = np.array([[1,3,2],
              [2,1,2],
              [1,3,1],
              [2,3,1]])
N = np.array([[6,2,1],
              [2,3,1],
              [3,4,1],
              [3,1,4]])
#hallar producto punto
#O = np.dot(M,N)
O = np.dot(M,np.transpose(N))
imprimir(M,N,O)

..........................
..........................
El primer arreglo es : 
[[1 3 2]
 [2 1 2]
 [1 3 1]
 [2 3 1]]
..........................
..........................
El segundo arreglo es : 
[[6 2 1]
 [2 3 1]
 [3 4 1]
 [3 1 4]]
..........................
..........................
el valor del resultado es : 
[[14 13 17 14]
 [16  9 12 15]
 [13 12 16 10]
 [19 14 19 13]]


### **Algunas funciones más**

En las siguientes lineas, se verán algunas funciones más

In [32]:
#Creación de matrices: 

# Matrices de ceros: 

matriz_ceros = np.zeros((3,2),dtype=int)

# Matrices de unos: 

matriz_unos = np.zeros((3,2),dtype=int)

#matriz identidad :

matriz_indetidad = np.identity(4,dtype=int)

#matriz diagonal: 
matriz_diagonal = np.eye(3,2,dtype= int)

imprimir_valores(matriz_ceros, matriz_unos, matriz_indetidad, matriz_diagonal)

..................
[[0 0]
 [0 0]
 [0 0]]
..................
[[0 0]
 [0 0]
 [0 0]]
..................
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
..................
[[1 0]
 [0 1]
 [0 0]]


In [40]:
# creación de matrices aleaotrias: 

matriz_ale = np.round(np.random.rand(4,2),2)

In [47]:
#Rangos largos: 

#Linspace: 

lin = np.linspace(1,5,25)
lin_list = list(lin)
# Logspace: 

log = np.logspace(2,10,10)

#Concatenar :
concat1 = np.concatenate((M,N),0)
concat2 = np.concatenate((M,N),1)

imprimir_valores(lin,lin_list,log,M,N,concat1,concat2)

..................
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]
..................
[1.0, 1.1666666666666667, 1.3333333333333333, 1.5, 1.6666666666666665, 1.8333333333333333, 2.0, 2.1666666666666665, 2.333333333333333, 2.5, 2.6666666666666665, 2.833333333333333, 3.0, 3.1666666666666665, 3.333333333333333, 3.5, 3.6666666666666665, 3.833333333333333, 4.0, 4.166666666666666, 4.333333333333333, 4.5, 4.666666666666666, 4.833333333333333, 5.0]
..................
[1.00000000e+02 7.74263683e+02 5.99484250e+03 4.64158883e+04
 3.59381366e+05 2.78255940e+06 2.15443469e+07 1.66810054e+08
 1.29154967e+09 1.00000000e+10]
..................
[[1 3 2]
 [2 1 2]
 [1 3 1]
 [2 3 1]]
..................
[[6 2 1]
 [2 3 1]
 [3 4 1]
 [3 1 4]]
..................
[[1 3 2]
 [2 1 2]
 